### ISSUE TITLE
Getting a wildcard directive warning from an OWASP zap scan that uses htmlunit-csp 

### ISSUE THREAD

**Issue by rubin55** [HtmlUnit/htmlunit-csp#6]
I'm getting a `CSP: Wildcard Directive` medium-level warning from an OWASP zap scan that utilizes `htmlunit-csp` to determine the quality/security of a policy. This is when given the following policy:

    default-src 'self'; script-src 'sha256-V9aCN36/azMjZ4UI2Gn224a5ZheabkDM9KlfEYVxacE=' 'sha256-2Az4yarMUUN/qlp7SBuAZ2xzTgO2hWYIiQ+FQuy/F7U='; style-src 'self' 'sha256-e/YMGdDlQb+SQxsaWl4HPQFw1kHpLE7FsvDQ3omByuU='; img-src 'self' data:; font-src 'self' data:; frame-ancestors 'none'; object-src 'none'; base-uri 'none';

As far as I can tell, the above does not contain a wildcard directive, although, I am no expert on the intricacies of these kind of policies. Is the above indeed a false positive caused by a wrong determination of `htmlunit-csp` or am I not parsing the above policy correctly and is there indeed something in there that causes it to be considered as a wildcard directive?

**Comment by rbri** [comment]
Will have a look....

**Comment by rbri** [comment]
Can you please provide the whole msg with all details...

I simply found this page https://www.zaproxy.org/docs/alerts/10055-4/ containing this statement:

The following directives either allow wildcard sources (or ancestors), **are not defined**, or are overly broadly defined: **connect-src**.

Maybe this is is the reason????

**Comment by rubin55** [comment]
Hi  @rbri thanks for taking a look. I think that's it, I must be dense (it's been a long tuesday); I'll have a look-see and see what the OWASP zap-test does when I add connect-src to the policy. Thanks a lot + sorry for the I-did-not-RTFM-hard-enough!

**Comment by rbri** [comment]
> I must be dense (it's been a long tuesday)

I know this kind of days :-) - no worries

**Comment by rubin55** [comment]
@rbri I was discussing this with colleagues this morning, and connect-src missing should default-src which we set to self in this policy; are you aware of specific issues when connect-src is not defined that would neccesitate triggering this warning?

**Comment by rbri** [comment]
@rubin55 not really, i have more or less cloned this lib and applied some outstanding patches and improvments. Maybe that is something we have to discuss with the zac peoples..

@kingthorin?

**Comment by kingthorin** [comment]
I believe connect-src is amongst those that don't fallback. I'll dig into docs and see if something has changed or if I've gotten something wrong.

Either way this is a ZAP issue not an htmlunit-csp issue. So @rubin55  if you could create an issue here:    https://github.com/zaproxy/zaproxy/issues/new?assignees=&labels=bug&projects=&template=bug-report.yml and close this one that's probably best.
(You could link this issue in the "Additional context" field)

> [!NOTE]
> ZAP left OWASP over a year ago :wink:

**Comment by kingthorin** [comment]
Oh `connect-src` isn't specific to this issue that's just the doc's example alert.

The item that's actually wrong in your CSP should be listed in either the specific alert's Description or Other Info field.

**Comment by kingthorin** [comment]
Specific to the CSP listed in the original issue above:

> The directive(s): form-action are among the directives that do not fallback to default-src, missing/excluding them is the same as allowing anything.

This issue can be closed and there's no need to raise one for ZAP.
If you have further questions/concerns please follow-up via the [ZAP User Group](https://groups.google.com/g/zaproxy-users).
